[profile.default]
src = "src"
out = "out"
libs = ["lib"]
is-system = true
viaIR = true
optimizer = true
optimizer_runs = 200

[profile.solx]
solc_version = "/home/mbarr/.local/bin/solx"
src = "src"
out = "out"
libs = ["lib"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
